// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRWtU9og08TBIKKLiEV4tO7voCJgHjiM',
    appId: '1:748044444926:web:917aae66082f60c43bb1af',
    messagingSenderId: '748044444926',
    projectId: 'to-do-app-6b09b',
    authDomain: 'to-do-app-6b09b.firebaseapp.com',
    storageBucket: 'to-do-app-6b09b.firebasestorage.app',
    measurementId: 'G-594F79ZH02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOIIMaCaAgEaatzbtSqV954_e2O0fIEAc',
    appId: '1:748044444926:android:99edfcdf0342a2173bb1af',
    messagingSenderId: '748044444926',
    projectId: 'to-do-app-6b09b',
    storageBucket: 'to-do-app-6b09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnuilXV-0rkm9TWPRtLRlC6-sDROO6rd4',
    appId: '1:748044444926:ios:9565a00c7419c15c3bb1af',
    messagingSenderId: '748044444926',
    projectId: 'to-do-app-6b09b',
    storageBucket: 'to-do-app-6b09b.firebasestorage.app',
    iosClientId: '748044444926-ifq131dj2gqj0vuvjctvicdrsu6j3uhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnuilXV-0rkm9TWPRtLRlC6-sDROO6rd4',
    appId: '1:748044444926:ios:9565a00c7419c15c3bb1af',
    messagingSenderId: '748044444926',
    projectId: 'to-do-app-6b09b',
    storageBucket: 'to-do-app-6b09b.firebasestorage.app',
    iosClientId: '748044444926-ifq131dj2gqj0vuvjctvicdrsu6j3uhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByRWtU9og08TBIKKLiEV4tO7voCJgHjiM',
    appId: '1:748044444926:web:7ec2f662d25ea6b23bb1af',
    messagingSenderId: '748044444926',
    projectId: 'to-do-app-6b09b',
    authDomain: 'to-do-app-6b09b.firebaseapp.com',
    storageBucket: 'to-do-app-6b09b.firebasestorage.app',
    measurementId: 'G-HW9DRN966B',
  );
}
