// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivupmhRQaTwdvjOwfGKMoxf_PXM9fLjA',
    appId: '1:877600725351:web:26fdbc528ba5c9471ef7c2',
    messagingSenderId: '877600725351',
    projectId: 'todo-app-29827',
    authDomain: 'todo-app-29827.firebaseapp.com',
    storageBucket: 'todo-app-29827.firebasestorage.app',
    measurementId: 'G-3M1SKNEQC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6Rse7XCDu1dxD1PWYe-F2VvRvL733RI',
    appId: '1:877600725351:android:d51bd5f6b690f30e1ef7c2',
    messagingSenderId: '877600725351',
    projectId: 'todo-app-29827',
    storageBucket: 'todo-app-29827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkQd0AvShVXHL5MlcbB21XyYQwWZQBxU',
    appId: '1:877600725351:ios:540db8e4dce447b01ef7c2',
    messagingSenderId: '877600725351',
    projectId: 'todo-app-29827',
    storageBucket: 'todo-app-29827.firebasestorage.app',
    iosClientId: '877600725351-2bfe7u6vkatf73nr4ce7nss0nbkv0iuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkQd0AvShVXHL5MlcbB21XyYQwWZQBxU',
    appId: '1:877600725351:ios:540db8e4dce447b01ef7c2',
    messagingSenderId: '877600725351',
    projectId: 'todo-app-29827',
    storageBucket: 'todo-app-29827.firebasestorage.app',
    iosClientId: '877600725351-2bfe7u6vkatf73nr4ce7nss0nbkv0iuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDivupmhRQaTwdvjOwfGKMoxf_PXM9fLjA',
    appId: '1:877600725351:web:f1f9990ee4a008a91ef7c2',
    messagingSenderId: '877600725351',
    projectId: 'todo-app-29827',
    authDomain: 'todo-app-29827.firebaseapp.com',
    storageBucket: 'todo-app-29827.firebasestorage.app',
    measurementId: 'G-Z2Y2PH739T',
  );
}
